### ISSUE TITLE
broken workaround

### ISSUE THREAD

**Issue by rahiel** [sachapan/ansible#1]
Hi,

Sorry for the inconvenience in https://github.com/sachapan/ansible/commit/ecb700ce95f32b72022811df4f9818fd11db4be3

This workaround is not necessary with the latest release of telegram-send (version 0.35).
And that version depends on the latest version of python-telegram-bot so I expect this work around breaks on the latest release.

**Comment by sachapan** [comment]
I appreciate your feedback, @rahiel, I have removed the workaround from my ansible script and tested it successfully.

Thank you
